#!/bin/bash

curl -fLo curl ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir -p ~/.config/nvim/

rm -f ~/.vimrc
ln -s `pwd`/vimrc ~/.vimrc
rm -fr ~/.config/nvim/init.vim
ln -s `pwd`/vimrc ~/.config/nvim/init.vim
